// Supplied official-source directory. Availability and deadlines must be confirmed at each source.
const opportunityDataset = {
    "dataset_name":  "Verified Real Opportunities - Official Sources",
    "version":  "1.0",
    "generated_date":  "2026-10-08",
    "record_count":  100,
    "scope":  "Scholarships, bursaries, internships, fellowships, jobs, graduate programmes, grants and youth/business opportunities.",
    "verification_policy":  "Each record points to an official government, intergovernmental organisation, university, foundation or company source. This dataset does not claim that every programme is open on the generated date; users must confirm the current call/deadline on the linked official source.",
    "records":  [
                    {
                        "id":  "OPP-001",
                        "opportunity_name":  "Western Cape Government Graduate Internship Programme",
                        "type":  "Internship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Western Cape Government",
                        "application_or_information_url":  "https://www.westerncape.gov.za/jobs-bursaries-and-tenders",
                        "verification":  "Official provincial government opportunity page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-002",
                        "opportunity_name":  "Western Cape Government Bursaries, Internships and Learnerships",
                        "type":  "Bursary/Internship/Learnership",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Western Cape Government",
                        "application_or_information_url":  "https://www.westerncape.gov.za/bursaries-internships-and-learnerships",
                        "verification":  "Official provincial government opportunity hub",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-003",
                        "opportunity_name":  "Western Cape Government First Work Experience PAY Programme",
                        "type":  "Work experience",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Western Cape Government",
                        "application_or_information_url":  "https://www.westerncape.gov.za/service/first-work-experience-pay-programme-0",
                        "verification":  "Official provincial government programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-004",
                        "opportunity_name":  "Western Cape Government Youth Opportunity Hub",
                        "type":  "Jobs/Internships/Learnerships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Western Cape Government",
                        "application_or_information_url":  "https://www.westerncape.gov.za/edat/youth",
                        "verification":  "Official provincial government youth hub",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-005",
                        "opportunity_name":  "SAYouth",
                        "type":  "Jobs/Learnerships/Internships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "SA Youth / Presidential Youth Employment Intervention",
                        "application_or_information_url":  "https://sayouth.mobi/",
                        "verification":  "Official youth employment platform",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-006",
                        "opportunity_name":  "NYDA Opportunities",
                        "type":  "Jobs/Bursaries/Business/Training",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/Opportunities.html",
                        "verification":  "Official South African government agency opportunity page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-007",
                        "opportunity_name":  "NYDA Grant Programme",
                        "type":  "Grant",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/",
                        "verification":  "Official government youth grant programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-008",
                        "opportunity_name":  "NYDA Youth Cooperative Development Programme",
                        "type":  "Business support",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/",
                        "verification":  "Official government youth programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-009",
                        "opportunity_name":  "NYDA Market Linkages Programme",
                        "type":  "Business support",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/",
                        "verification":  "Official government youth programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-010",
                        "opportunity_name":  "NYDA Mentorship Programme",
                        "type":  "Mentorship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/",
                        "verification":  "Official government youth programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-011",
                        "opportunity_name":  "NYDA Job Preparedness Programme",
                        "type":  "Career preparation",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Youth Development Agency",
                        "application_or_information_url":  "https://www.nyda.gov.za/",
                        "verification":  "Official government youth programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-012",
                        "opportunity_name":  "NSFAS Funding",
                        "type":  "Financial aid",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Student Financial Aid Scheme",
                        "application_or_information_url":  "https://www.nsfas.org.za/",
                        "verification":  "Official public student funding scheme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-013",
                        "opportunity_name":  "Funza Lushaka Bursary Programme",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Department of Basic Education / Funza Lushaka",
                        "application_or_information_url":  "https://www.funzalushaka.doe.gov.za/",
                        "verification":  "Official teacher bursary programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-014",
                        "opportunity_name":  "DHET International Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "International/South Africa",
                        "provider":  "Department of Higher Education and Training",
                        "application_or_information_url":  "https://www.internationalscholarships.dhet.gov.za/",
                        "verification":  "Official South African government scholarship portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-015",
                        "opportunity_name":  "National Treasury External Bursary",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Treasury",
                        "application_or_information_url":  "https://www.treasury.gov.za/graduate/",
                        "verification":  "Official National Treasury graduate/bursary page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-016",
                        "opportunity_name":  "National Treasury Chartered Accountants Academy",
                        "type":  "Graduate programme",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Treasury",
                        "application_or_information_url":  "https://www.treasury.gov.za/graduate/",
                        "verification":  "Official National Treasury graduate programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-017",
                        "opportunity_name":  "NRF Postgraduate Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official national research funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-018",
                        "opportunity_name":  "NRF SARAO Honours Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation / SARAO",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official NRF funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-019",
                        "opportunity_name":  "NRF SARAO Masters Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation / SARAO",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official NRF funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-020",
                        "opportunity_name":  "NRF SARAO Doctoral Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation / SARAO",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official NRF funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-021",
                        "opportunity_name":  "NRF Postdoctoral Grants",
                        "type":  "Postdoctoral grant",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official NRF funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-022",
                        "opportunity_name":  "NRF Thuthuka Funding",
                        "type":  "Research grant",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "National Research Foundation",
                        "application_or_information_url":  "https://www.nrf.ac.za/funding/nrf-call-for-proposals-for-funding-in-2026-and-2027/",
                        "verification":  "Official NRF funding call",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-023",
                        "opportunity_name":  "CSIR Bursaries",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Council for Scientific and Industrial Research",
                        "application_or_information_url":  "https://www.csir.co.za/bursaries",
                        "verification":  "Official public research organisation bursary page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-024",
                        "opportunity_name":  "Transnet Bursary Scheme",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Transnet",
                        "application_or_information_url":  "https://www.transnet.net/",
                        "verification":  "Official state-owned company careers/bursary source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-025",
                        "opportunity_name":  "SARB Bursary Scheme",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "South African Reserve Bank",
                        "application_or_information_url":  "https://www.resbank.co.za/en/home/careers",
                        "verification":  "Official central bank careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-026",
                        "opportunity_name":  "SARB Data Science and Machine Learning Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "South African Reserve Bank",
                        "application_or_information_url":  "https://www.resbank.co.za/en/home/careers",
                        "verification":  "Official central bank scholarship/careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-027",
                        "opportunity_name":  "SANSA Graduate Internship Programme",
                        "type":  "Internship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "South African National Space Agency",
                        "application_or_information_url":  "https://www.sansa.org.za/careers/",
                        "verification":  "Official national space agency careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-028",
                        "opportunity_name":  "SAHPRA Graduate Internship Programme",
                        "type":  "Internship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "South African Health Products Regulatory Authority",
                        "application_or_information_url":  "https://www.sahpra.org.za/careers/",
                        "verification":  "Official regulator careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-029",
                        "opportunity_name":  "Department of Agriculture Bursaries and Internships",
                        "type":  "Bursary/Internship",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Department of Agriculture",
                        "application_or_information_url":  "https://nda.gov.za/index.php/vacancies",
                        "verification":  "Official national department opportunity page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-030",
                        "opportunity_name":  "Department of Mineral and Petroleum Resources Bursaries",
                        "type":  "Bursary",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Department of Mineral and Petroleum Resources",
                        "application_or_information_url":  "https://www.dmpr.gov.za/Media-Centre/Learning-Opportunities",
                        "verification":  "Official national department learning opportunities page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-031",
                        "opportunity_name":  "South African Government Jobs",
                        "type":  "Government jobs",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "South African Government",
                        "application_or_information_url":  "https://www.gov.za/about-government/government-jobs",
                        "verification":  "Official government jobs information",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-032",
                        "opportunity_name":  "UCT Financial Aid",
                        "type":  "Financial aid",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of Cape Town",
                        "application_or_information_url":  "https://www.uct.ac.za/students/funding-financial-aid",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-033",
                        "opportunity_name":  "UCT Postgraduate Funding",
                        "type":  "Scholarship/Funding",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of Cape Town",
                        "application_or_information_url":  "https://www.uct.ac.za/students/funding-financial-aid",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-034",
                        "opportunity_name":  "Stellenbosch University Bursaries and Funding",
                        "type":  "Bursary/Funding",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Stellenbosch University",
                        "application_or_information_url":  "https://www.sun.ac.za/english/maties/Pages/Bursaries.aspx",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-035",
                        "opportunity_name":  "University of the Western Cape Financial Aid",
                        "type":  "Financial aid",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of the Western Cape",
                        "application_or_information_url":  "https://www.uwc.ac.za/Students/Pages/Financial-Aid.aspx",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-036",
                        "opportunity_name":  "CPUT Student Funding",
                        "type":  "Financial aid",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Cape Peninsula University of Technology",
                        "application_or_information_url":  "https://www.cput.ac.za/students/funding",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-037",
                        "opportunity_name":  "Wits Financial Aid",
                        "type":  "Financial aid",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of the Witwatersrand",
                        "application_or_information_url":  "https://www.wits.ac.za/students/financial-aid-and-scholarships/",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-038",
                        "opportunity_name":  "University of Pretoria Funding",
                        "type":  "Funding/Scholarships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of Pretoria",
                        "application_or_information_url":  "https://www.up.ac.za/student-funding",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-039",
                        "opportunity_name":  "University of Johannesburg Funding",
                        "type":  "Funding/Scholarships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of Johannesburg",
                        "application_or_information_url":  "https://www.uj.ac.za/study-at-uj/fees-and-funding/",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-040",
                        "opportunity_name":  "Rhodes University Funding",
                        "type":  "Funding/Scholarships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "Rhodes University",
                        "application_or_information_url":  "https://www.ru.ac.za/studentbureau/funding/",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-041",
                        "opportunity_name":  "UKZN Financial Aid and Scholarships",
                        "type":  "Funding/Scholarships",
                        "location_or_eligibility":  "South Africa",
                        "provider":  "University of KwaZulu-Natal",
                        "application_or_information_url":  "https://ukzn.ac.za/student-fees-and-financial-aid/",
                        "verification":  "Official university funding source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-042",
                        "opportunity_name":  "Chevening Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom/Global",
                        "provider":  "UK Foreign, Commonwealth \u0026 Development Office",
                        "application_or_information_url":  "https://www.chevening.org/scholarships/",
                        "verification":  "Official UK government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-043",
                        "opportunity_name":  "Commonwealth Master\u0027s Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "UK/Commonwealth",
                        "provider":  "Commonwealth Scholarship Commission",
                        "application_or_information_url":  "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
                        "verification":  "Official UK government-funded scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-044",
                        "opportunity_name":  "Commonwealth PhD Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "UK/Commonwealth",
                        "provider":  "Commonwealth Scholarship Commission",
                        "application_or_information_url":  "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-phd-scholarships/",
                        "verification":  "Official scholarship commission",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-045",
                        "opportunity_name":  "Gates Cambridge Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Cambridge",
                        "application_or_information_url":  "https://www.gatescambridge.org/scholarships/",
                        "verification":  "Official Cambridge scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-046",
                        "opportunity_name":  "Cambridge Trust Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Cambridge",
                        "application_or_information_url":  "https://www.cambridgetrust.org/scholarships/",
                        "verification":  "Official university trust",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-047",
                        "opportunity_name":  "Rhodes Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Global",
                        "provider":  "Rhodes Trust",
                        "application_or_information_url":  "https://www.rhodeshouse.ox.ac.uk/scholarships/",
                        "verification":  "Official Rhodes Trust scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-048",
                        "opportunity_name":  "Clarendon Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Oxford",
                        "application_or_information_url":  "https://www.ox.ac.uk/clarendon",
                        "verification":  "Official Oxford scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-049",
                        "opportunity_name":  "Reach Oxford Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Oxford",
                        "application_or_information_url":  "https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship",
                        "verification":  "Official Oxford scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-050",
                        "opportunity_name":  "Ertegun Graduate Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Oxford",
                        "application_or_information_url":  "https://www.ertegun.ox.ac.uk/",
                        "verification":  "Official Oxford scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-051",
                        "opportunity_name":  "Weidenfeld and Hoffmann Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United Kingdom",
                        "provider":  "University of Oxford",
                        "application_or_information_url":  "https://www.ox.ac.uk/admissions/graduate/fees-and-funding/oxford-funding/weidenfeld-and-hoffmann-scholarships-and-leadership-programme",
                        "verification":  "Official Oxford scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-052",
                        "opportunity_name":  "Knight-Hennessy Scholars",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United States",
                        "provider":  "Stanford University",
                        "application_or_information_url":  "https://knight-hennessy.stanford.edu/",
                        "verification":  "Official Stanford graduate scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-053",
                        "opportunity_name":  "Fulbright Foreign Student Program",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United States/Global",
                        "provider":  "U.S. Department of State",
                        "application_or_information_url":  "https://foreign.fulbrightonline.org/",
                        "verification":  "Official U.S. government programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-054",
                        "opportunity_name":  "Humphrey Fellowship Program",
                        "type":  "Fellowship",
                        "location_or_eligibility":  "United States/Global",
                        "provider":  "U.S. Department of State",
                        "application_or_information_url":  "https://www.humphreyfellowship.org/",
                        "verification":  "Official U.S. government fellowship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-055",
                        "opportunity_name":  "Gilman Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "United States",
                        "provider":  "U.S. Department of State",
                        "application_or_information_url":  "https://www.gilmanscholarship.org/",
                        "verification":  "Official U.S. government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-056",
                        "opportunity_name":  "Boren Awards",
                        "type":  "Scholarship/Fellowship",
                        "location_or_eligibility":  "United States",
                        "provider":  "U.S. Department of Defense",
                        "application_or_information_url":  "https://www.borenawards.org/",
                        "verification":  "Official U.S. government-funded programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-057",
                        "opportunity_name":  "Schwarzman Scholars",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "China/Global",
                        "provider":  "Schwarzman Scholars",
                        "application_or_information_url":  "https://www.schwarzmanscholars.org/",
                        "verification":  "Official programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-058",
                        "opportunity_name":  "Yenching Academy Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "China/Global",
                        "provider":  "Peking University",
                        "application_or_information_url":  "https://yenchingacademy.pku.edu.cn/",
                        "verification":  "Official university academy",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-059",
                        "opportunity_name":  "MEXT Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Japan/Global",
                        "provider":  "Government of Japan",
                        "application_or_information_url":  "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",
                        "verification":  "Official Japanese government study portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-060",
                        "opportunity_name":  "DAAD Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Germany/Global",
                        "provider":  "DAAD",
                        "application_or_information_url":  "https://www.daad.de/en/studying-in-germany/scholarships/",
                        "verification":  "Official German Academic Exchange Service",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-061",
                        "opportunity_name":  "Erasmus Mundus Joint Masters",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Europe/Global",
                        "provider":  "European Commission",
                        "application_or_information_url":  "https://education.ec.europa.eu/education-levels/higher-education/inclusive-and-connected-higher-education/erasmus-mundus-joint-masters",
                        "verification":  "Official European Commission programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-062",
                        "opportunity_name":  "Erasmus+ Opportunities",
                        "type":  "Study/Training/Youth",
                        "location_or_eligibility":  "Europe/Global",
                        "provider":  "European Commission",
                        "application_or_information_url":  "https://erasmus-plus.ec.europa.eu/",
                        "verification":  "Official European Union programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-063",
                        "opportunity_name":  "Marie SkÅ‚odowska-Curie Actions",
                        "type":  "Fellowship/Research",
                        "location_or_eligibility":  "Europe/Global",
                        "provider":  "European Commission",
                        "application_or_information_url":  "https://marie-sklodowska-curie-actions.ec.europa.eu/",
                        "verification":  "Official EU research programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-064",
                        "opportunity_name":  "Swiss Government Excellence Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Switzerland/Global",
                        "provider":  "Swiss Government",
                        "application_or_information_url":  "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
                        "verification":  "Official Swiss government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-065",
                        "opportunity_name":  "Swedish Institute Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Sweden/Global",
                        "provider":  "Swedish Institute",
                        "application_or_information_url":  "https://si.se/en/apply/scholarships/",
                        "verification":  "Official Swedish government agency",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-066",
                        "opportunity_name":  "Australia Awards Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Australia/Global",
                        "provider":  "Australian Government",
                        "application_or_information_url":  "https://www.dfat.gov.au/people-to-people/australia-awards",
                        "verification":  "Official Australian government programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-067",
                        "opportunity_name":  "New Zealand Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "New Zealand/Global",
                        "provider":  "New Zealand Government",
                        "application_or_information_url":  "https://www.nzscholarships.govt.nz/",
                        "verification":  "Official New Zealand government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-068",
                        "opportunity_name":  "TÃ¼rkiye Scholarships",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "TÃ¼rkiye/Global",
                        "provider":  "Government of TÃ¼rkiye",
                        "application_or_information_url":  "https://www.turkiyeburslari.gov.tr/",
                        "verification":  "Official Turkish government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-069",
                        "opportunity_name":  "Stipendium Hungaricum",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Hungary/Global",
                        "provider":  "Government of Hungary",
                        "application_or_information_url":  "https://stipendiumhungaricum.hu/",
                        "verification":  "Official Hungarian government scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-070",
                        "opportunity_name":  "Korean Government Scholarship (GKS)",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "South Korea/Global",
                        "provider":  "Government of South Korea",
                        "application_or_information_url":  "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
                        "verification":  "Official Korean government study portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-071",
                        "opportunity_name":  "Ireland Government Postgraduate Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Ireland/Global",
                        "provider":  "Government of Ireland / Research Ireland",
                        "application_or_information_url":  "https://research.ie/funding/goipg/",
                        "verification":  "Official Irish research funding",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-072",
                        "opportunity_name":  "Netherlands NL Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Netherlands/Global",
                        "provider":  "Dutch Ministry of Education / participating institutions",
                        "application_or_information_url":  "https://www.studyinnl.org/finances/nl-scholarship",
                        "verification":  "Official Study in NL source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-073",
                        "opportunity_name":  "Orange Knowledge Programme",
                        "type":  "Scholarship/Training",
                        "location_or_eligibility":  "Netherlands/International",
                        "provider":  "Netherlands government programme",
                        "application_or_information_url":  "https://www.studyinnl.org/finances/orange-knowledge-programme",
                        "verification":  "Official Study in NL information",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-074",
                        "opportunity_name":  "Aga Khan Foundation International Scholarship Programme",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Global",
                        "provider":  "Aga Khan Foundation",
                        "application_or_information_url":  "https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
                        "verification":  "Official foundation programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-075",
                        "opportunity_name":  "Mastercard Foundation Scholars Program",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Africa/Global",
                        "provider":  "Mastercard Foundation",
                        "application_or_information_url":  "https://mastercardfdn.org/all/scholars/",
                        "verification":  "Official foundation programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-076",
                        "opportunity_name":  "Mandela Rhodes Scholarship",
                        "type":  "Scholarship",
                        "location_or_eligibility":  "Africa/South Africa",
                        "provider":  "Mandela Rhodes Foundation",
                        "application_or_information_url":  "https://www.mandelarhodes.org/scholarship/",
                        "verification":  "Official foundation scholarship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-077",
                        "opportunity_name":  "Mo Ibrahim Foundation Leadership Fellowship",
                        "type":  "Fellowship",
                        "location_or_eligibility":  "Africa",
                        "provider":  "Mo Ibrahim Foundation",
                        "application_or_information_url":  "https://mo.ibrahim.foundation/fellowships",
                        "verification":  "Official foundation fellowship",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-078",
                        "opportunity_name":  "One Young World Scholarships",
                        "type":  "Scholarship/Fellowship",
                        "location_or_eligibility":  "Global",
                        "provider":  "One Young World",
                        "application_or_information_url":  "https://www.oneyoungworld.com/scholarships",
                        "verification":  "Official summit scholarship page",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-079",
                        "opportunity_name":  "African Union Youth Volunteer Corps",
                        "type":  "Volunteer/Fellowship",
                        "location_or_eligibility":  "Africa",
                        "provider":  "African Union",
                        "application_or_information_url":  "https://au.int/en/ayvc",
                        "verification":  "Official African Union programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-080",
                        "opportunity_name":  "African Union Internship Programme",
                        "type":  "Internship",
                        "location_or_eligibility":  "Africa",
                        "provider":  "African Union",
                        "application_or_information_url":  "https://au.int/en/internship",
                        "verification":  "Official African Union programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-081",
                        "opportunity_name":  "UN Secretariat Jobs",
                        "type":  "Jobs",
                        "location_or_eligibility":  "Global",
                        "provider":  "United Nations",
                        "application_or_information_url":  "https://careers.un.org/jobsearch",
                        "verification":  "Official UN careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-082",
                        "opportunity_name":  "UN Young Professionals Programme",
                        "type":  "Early career",
                        "location_or_eligibility":  "Global",
                        "provider":  "United Nations",
                        "application_or_information_url":  "https://careers.un.org/jobsearch",
                        "verification":  "Official UN careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-083",
                        "opportunity_name":  "UN Internships",
                        "type":  "Internship",
                        "location_or_eligibility":  "Global",
                        "provider":  "United Nations",
                        "application_or_information_url":  "https://careers.un.org/jobsearch",
                        "verification":  "Official UN careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-084",
                        "opportunity_name":  "UN Volunteers",
                        "type":  "Volunteer",
                        "location_or_eligibility":  "Global",
                        "provider":  "United Nations Volunteers",
                        "application_or_information_url":  "https://app.unv.org/",
                        "verification":  "Official UN volunteer platform",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-085",
                        "opportunity_name":  "UNDP Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "United Nations Development Programme",
                        "application_or_information_url":  "https://jobs.undp.org/",
                        "verification":  "Official UNDP jobs platform",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-086",
                        "opportunity_name":  "UNICEF Careers",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "UNICEF",
                        "application_or_information_url":  "https://jobs.unicef.org/",
                        "verification":  "Official UNICEF careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-087",
                        "opportunity_name":  "WHO Careers",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "World Health Organization",
                        "application_or_information_url":  "https://www.who.int/careers",
                        "verification":  "Official WHO careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-088",
                        "opportunity_name":  "UNESCO Careers and Internships",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "UNESCO",
                        "application_or_information_url":  "https://careers.unesco.org/",
                        "verification":  "Official UNESCO careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-089",
                        "opportunity_name":  "ILO Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "International Labour Organization",
                        "application_or_information_url":  "https://jobs.ilo.org/",
                        "verification":  "Official ILO careers portal",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-090",
                        "opportunity_name":  "FAO Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "Food and Agriculture Organization",
                        "application_or_information_url":  "https://www.fao.org/employment/home/en/",
                        "verification":  "Official FAO careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-091",
                        "opportunity_name":  "UNHCR Jobs",
                        "type":  "Jobs",
                        "location_or_eligibility":  "Global",
                        "provider":  "UNHCR",
                        "application_or_information_url":  "https://www.unhcr.org/careers",
                        "verification":  "Official UNHCR careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-092",
                        "opportunity_name":  "WFP Careers",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "World Food Programme",
                        "application_or_information_url":  "https://www.wfp.org/careers",
                        "verification":  "Official WFP careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-093",
                        "opportunity_name":  "UNFPA Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "UNFPA",
                        "application_or_information_url":  "https://www.unfpa.org/jobs",
                        "verification":  "Official UNFPA jobs source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-094",
                        "opportunity_name":  "UN Women Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "UN Women",
                        "application_or_information_url":  "https://jobs.undp.org/cj_view_jobs.cfm?cur_rgn_id=world",
                        "verification":  "Official UN system recruitment source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-095",
                        "opportunity_name":  "World Bank Jobs",
                        "type":  "Jobs/Internships",
                        "location_or_eligibility":  "Global",
                        "provider":  "World Bank Group",
                        "application_or_information_url":  "https://www.worldbank.org/en/about/careers",
                        "verification":  "Official World Bank careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-096",
                        "opportunity_name":  "World Bank Young Professionals Program",
                        "type":  "Early career",
                        "location_or_eligibility":  "Global",
                        "provider":  "World Bank Group",
                        "application_or_information_url":  "https://www.worldbank.org/en/about/careers/programs-and-internships/young-professionals-program",
                        "verification":  "Official World Bank programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-097",
                        "opportunity_name":  "World Bank Group Internship Program",
                        "type":  "Internship",
                        "location_or_eligibility":  "Global",
                        "provider":  "World Bank Group",
                        "application_or_information_url":  "https://www.worldbank.org/en/about/careers/programs-and-internships/internship",
                        "verification":  "Official World Bank internship programme",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-098",
                        "opportunity_name":  "IMF Fund Internship Program",
                        "type":  "Internship",
                        "location_or_eligibility":  "Global",
                        "provider":  "International Monetary Fund",
                        "application_or_information_url":  "https://www.imf.org/en/about/careers",
                        "verification":  "Official IMF careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-099",
                        "opportunity_name":  "IMF Research Analyst Program",
                        "type":  "Early career",
                        "location_or_eligibility":  "Global",
                        "provider":  "International Monetary Fund",
                        "application_or_information_url":  "https://www.imf.org/en/about/careers",
                        "verification":  "Official IMF careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    },
                    {
                        "id":  "OPP-100",
                        "opportunity_name":  "IMF Economist Program",
                        "type":  "Early career",
                        "location_or_eligibility":  "Global",
                        "provider":  "International Monetary Fund",
                        "application_or_information_url":  "https://www.imf.org/en/about/careers",
                        "verification":  "Official IMF careers source",
                        "verified_source_type":  "Official provider/government/university website",
                        "status_note":  "Availability and deadline can change; check the linked official page before applying.",
                        "last_verified":  "2026-10-08"
                    }
                ]
};

function getOpportunityCategories(type) {
  const categories = [];
  if (/scholarship|bursary|financial aid|funding/i.test(type)) categories.push("Funding & scholarships");
  if (/business|grant/i.test(type)) categories.push("Business & grants");
  if (/internship|graduate|early career|fellowship|postdoctoral/i.test(type)) categories.push("Internships & fellowships");
  if (/job|work experience/i.test(type)) categories.push("Jobs & work experience");
  if (/learnership|training|study|volunteer|mentorship|career preparation|youth/i.test(type)) categories.push("Training & youth programmes");
  return categories.length ? categories : ["Other opportunities"];
}

const opportunitiesData = opportunityDataset.records.map((record) => {
  const categories = getOpportunityCategories(record.type);
  return {
    ...record,
    title: record.opportunity_name,
    organisation: record.provider,
    category: categories[0],
    categories,
    location: record.location_or_eligibility,
    experienceLevel: "See official source",
    closingDate: "",
    shortDescription: record.status_note,
    fullDescription: `${record.verification}. ${record.status_note}`,
    requirements: [record.location_or_eligibility, record.verification, record.status_note],
    documentsRequired: [],
    applicationLink: record.application_or_information_url,
    updatedDate: record.last_verified
  };
});